#!/usr/bin/env python

import sys

from optparse import OptionParser
from pylint import checkers, lint

from DjangoLint import AstCheckers

def main():
    linter = lint.PyLinter()
    linter.set_option('reports', options['report'])
    checkers.initialize(linter)

    for msg in ('C0111', 'C0301'):
        linter.disable_message(msg)

    # Register custom checkers
    AstCheckers.register(linter)

    linter.check([name, 'settings'])

    return 0

if __name__ == "__main__":
    sys.exit(main())
